level_map = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'                                ',
'                                ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'    XXXX  XXXXXX   XX   XXXX    ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'    XXXX  XXXXXX   XX   XXXX    ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'                                ',
'                                ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'    XXXX  XXXXXX   XX   XXXX    ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'    XXXX  XXXXXX   XX   XXXX    ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'                                ',
'                                ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'    XXXX  XXXXXX   XX   XXXX    ',
' XX     XXX             XX      ',
' XX                             ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'    XXXX  XXXXXX   XX   XXXX    ',
' XX     XXX             XX      ',
' XX P                           ',
' XXXX         XX            XX  ',
' XXXX       XX                  ',
' XX    X  XXXX     XX   XX      ',
'       X  XXXX     XX   XXX     ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXX  XXXXXX   XX   XXXX    ']

tile_size = 64
screen_width = 1200
# screen_height = len(level_map) * tile_size
screen_height = 800